application: whotweetedthis
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /font
  static_dir: font

- url: /.*
  script: whotweetedthis.app
  
libraries:
- name: jinja2
  version: latest